# -*- coding: utf-8 -*-
"""Petshop.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_DXoHtuHTRbg6G1QyLbJYORi2KZw3ht

#Código do Petshop
"""

#Petshop
#Começo da função de peso
def cachorro_peso(): #Função do peso do cachorro
  print('------------------- Menu 1 de 3 - Peso do cachorro --------------------') #Menu do peso do cachorro
  while True: #Laço de repetição
    try: #Tentar executar com sucesso
     peso = int(input('Entre com o peso do cachorro(Kg):'))
     if peso < 3 and peso > 0:
      base = 40 #Valor da base para esse intervalo de peso
      return base #Salvar o valor da base para poder partir para o tipo de pelo

     if peso >= 3 and peso < 10:
      base = 50
      return base

     if peso >= 10 and peso < 30:
      base = 60
      return base

     if peso >= 30  and peso < 50:
      base = 70
      return base

     if peso >= 50: #Erro de cachorros acima do peso permitido
       print('Não aceitamos cachorros tão grandes.')
       print('Por favor entre com o peso do cachorro novamente.')
     else: #Caso o cliente digite 0 ou algum número negativo
       print('Por favor entre com o peso do cachorro novamente.')
       continue #Voltar para o início
    except ValueError: #Erro para valor não numérico ou algum número float Ex:1.5
      print('Você digitou um valor não numérico')
      print('Por favor entre com o peso do cachorro novamente.')
#Fim da função de peso


#Começo da função de pelo
def cachorro_pelo():
  print('------------------- Menu 2 de 3 - Pelo do cachorro --------------------')
  while True:
   pelo = input('Entre com o pelo do cachorro \n'+
                'c- Pelo Curto \n'+
                'm- Pelo Médio \n'+
                'l-Pelo Longo \n'+
                '>>')
   pelo = pelo.lower() #Passar a letra maiúscula que o cliente possa escrever para minúscula
   if pelo == 'c':
    return   1.00 #Por quanto que multiplica o valor da base

   elif pelo == 'm':
    return   1.50

   elif pelo == 'l':
    return   2.00
   else: #Caso dê algum erro no que o cliente digitar
    print('Você digitou uma opção diferente de (c/m/l).Tente novamente.')
    continue #Voltar para o início do while
#Fim da função de pelo

#Começo da função extra
def cachorro_extra():
  print('------------------- Menu 3 de 3 - Serviços Extra ----------------------')
  acumulador = 0
  while True:
    mais_serviço = input('Deseja adicionar mais algum serviço?\n'+
                         '1 - Corte de Unhas - R$10,00\n'+
                         '2 - Escovar Dentes - R$12,00\n'+
                         '3 - Limpeza de orelhas - R$15,00\n'+
                         '0 - Não desejo mais nada\n'+
                         '>>')
    if mais_serviço == '1':
      acumulador = acumulador + 10
      continue
    elif mais_serviço == '2':
      acumulador = acumulador + 12
      continue
    elif mais_serviço == '3':
      acumulador = acumulador + 15
      continue
    elif mais_serviço == '0':
      return acumulador #Cancela as perguntas por serviço extra e parte para o total do pedido
    else:
      print('Opção inválida.Tente novamente.') #Caso o cliente digite algum valor diferente de 0,1,2,3
      continue

#Fim da função extra

#Laço principal
print('------------------- Bem-vindo ao Petshop do Eduardo -------------------')

peso = cachorro_peso()
pelo =cachorro_pelo()
mais_serviço = cachorro_extra()

total = peso * pelo + mais_serviço

print('Total a pagar(R$):{:.2f} (Peso: R$ {:.2f} * Pelo: {:.2f} + Adicional(is): R$ {:.2f})'.format(total,peso,pelo,mais_serviço))# total do pedido